name: admin-backend
services:
  bitshala-db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bitshala
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
  mailcrab:
    image: marlonb/mailcrab:latest
    environment:
      ENABLE_TLS_AUTH: true
    ports:
      - "1080:1080"
      - "1025:1025"