db:
  postgres:
    host: localhost
    port: 5432
    username: root
    password: password
    databaseName: bitshala
  synchronize: true
cache:
  redis:
    url: redis://localhost:6379
discord:
  clientId: <discord_client_id>
  clientSecret: <discord_client_secret>
  botToken: <discord_bot_token>
  stateTtlSeconds: 300
  apiBaseUrl: 'https://discord.com/api/v10'
  oauthUrl: 'https://discord.com/oauth2/authorize'
  guildId: '1104831812720656540'
  authScopes:
    - identify
    - email
    - guilds
    - guilds.join
    - guilds.members.read
  roles:
    admin: '1104833385626607718'
    teachingAssistant: '1257350427565883494'
    masteringBitcoin: '1239628480111579268'
    learningBitcoinFromCommandLine: '1104833425623482368'
    programmingBitcoin: '1165952193556389928'
    bitcoinProtocolDevelopment: '1221081628021887009'
    masteringLightningNetwork: '1394917163957227671'
  inviteUrls:
    masteringBitcoin: https://discord.gg/PRYytp69TG
    learningBitcoinFromCommandLine: https://discord.gg/FCH4dCwyEk
    programmingBitcoin: https://discord.gg/MHcvqQsDHY
    bitcoinProtocolDevelopment: https://discord.gg/VT8tGxHZEC
    masteringLightningNetwork: https://discord.gg/3vweqyFcnR
app:
  baseUrl: 'http://localhost:3000'
  frontEndUrl: 'http://localhost:5173'
  port: 3000
  verbose: false
  debug: true
  auth:
    callbackPath: '/auth/discord/callback'
    dashboardRedirectPath: '/health'
    sessionTtlSeconds: 604800 # 7 days
email:
  smtp:
    host: localhost
    port: 1025
    secure: true
    user: admin
    pass: password
  from:
    email: noreply@bitshala.org # Sender email address
    name: Bitshala # Sender name
